"""All ladder networks of the CA glue filling station program, encoded for
the diagram renderer (see ladder_render.py for the element grammar).

Variable names are shown unqualified for drawing width; in CODESYS the
GVL_IO.* prefix is optional (no qualified_only attribute is set).
"""

NETWORKS = [
    # ---------------- SECTION A - SYSTEM UTILITIES ----------------
    dict(n=1, title="Flasher - half period A",
         rung=[("nc", "tBlinkB.Q"),
               ("fb", "TON", "tBlinkA", ["IN", "PT:=cfgBlinkHalfPeriod"], ["Q"])],
         outs=[]),
    dict(n=2, title="Flasher - half period B + Blink bit",
         rung=[("no", "tBlinkA.Q")],
         outs=[[("fb", "TON", "tBlinkB", ["IN", "PT:=cfgBlinkHalfPeriod"], ["Q"])],
               [("coil", "Blink")]]),

    # ---------------- SECTION B - INPUT CONDITIONING ----------------
    dict(n=3, title="Bottle present, debounced",
         rung=[("no", "I_BottlePresent"),
               ("fb", "TON", "tDbBotPres", ["IN", "PT:=cfgDebPresence"], ["Q"])],
         outs=[[("coil", "dbBottlePresent")]]),
    dict(n=4, title="Syringe present, debounced",
         rung=[("no", "I_SyrPresent"),
               ("fb", "TON", "tDbSyrPres", ["IN", "PT:=cfgDebPresence"], ["Q"])],
         outs=[[("coil", "dbSyrPresent")]]),
    dict(n=5, title="Syringe locked, debounced",
         rung=[("no", "I_SyrLocked"),
               ("fb", "TON", "tDbSyrLock", ["IN", "PT:=cfgDebPresence"], ["Q"])],
         outs=[[("coil", "dbSyrLocked")]]),
    dict(n=6, title="Syringe tip present, debounced",
         rung=[("no", "I_TipPresent"),
               ("fb", "TON", "tDbTipPres", ["IN", "PT:=cfgDebPresence"], ["Q"])],
         outs=[[("coil", "dbTipPresent")]]),
    dict(n=7, title="Bottle mode, debounced",
         rung=[("no", "I_BottleMode"),
               ("fb", "TON", "tDbModeB", ["IN", "PT:=cfgDebMode"], ["Q"])],
         outs=[[("coil", "ModeBottle")]]),
    dict(n=8, title="Syringe mode, debounced",
         rung=[("nc", "I_BottleMode"),
               ("fb", "TON", "tDbModeS", ["IN", "PT:=cfgDebMode"], ["Q"])],
         outs=[[("coil", "ModeSyringe")]]),
    dict(n=9, title="Pressure pot low level, anti-slosh",
         rung=[("nc", "I_PotLevelOK"),
               ("fb", "TON", "tDbPotLow", ["IN", "PT:=cfgDebPotLow"], ["Q"])],
         outs=[[("coil", "PotLow")]]),

    # ---------------- SECTION C - TWO-HAND CONTROL ----------------
    dict(n=10, title="Discordance timer - left button alone",
         rung=[("no", "I_BtnLeft"), ("nc", "I_BtnRight"),
               ("fb", "TON", "tDiscL", ["IN", "PT:=cfgSyncWindow"], ["Q"])],
         outs=[]),
    dict(n=11, title="Discordance timer - right button alone",
         rung=[("no", "I_BtnRight"), ("nc", "I_BtnLeft"),
               ("fb", "TON", "tDiscR", ["IN", "PT:=cfgSyncWindow"], ["Q"])],
         outs=[]),
    dict(n=12, title="Lockout: anti-tie-down + full-release re-initiation",
         rung=[("or", [[("no", "tDiscL.Q")],
                       [("no", "tDiscR.Q")],
                       [("no", "TwoHandOK"),
                        ("fb", "F_TRIG", "ftTwoHand", ["CLK"], ["Q"])],
                       [("no", "THC_Lockout")]]),
               ("or", [[("no", "I_BtnLeft")],
                       [("no", "I_BtnRight")]])],
         outs=[[("coil", "THC_Lockout")]]),
    dict(n=13, title="Two-hand valid",
         rung=[("no", "I_BtnLeft"), ("no", "I_BtnRight"), ("nc", "THC_Lockout")],
         outs=[[("coil", "TwoHandOK")]]),
    dict(n=14, title="Start pulse (rising edge = anti-repeat)",
         rung=[("no", "TwoHandOK"),
               ("fb", "R_TRIG", "trigStart", ["CLK"], ["Q"])],
         outs=[[("coil", "StartPulse")]]),
    dict(n=15, title="Fault-reset gesture: release both, then hold both 3 s",
         rung=[("or", [[("nc", "I_BtnLeft"), ("nc", "I_BtnRight")],
                       [("no", "ResetArmed")]]),
               ("or", [[("no", "FaultLatched")],
                       [("no", "EStopTrip")],
                       [("no", "SpillTrip")]])],
         outs=[[("coil", "ResetArmed")],
               [("no", "TwoHandOK"),
                ("fb", "TON", "tResetHold", ["IN", "PT:=cfgResetHold"], ["Q"]),
                ("fb", "R_TRIG", "trigReset", ["CLK"], ["Q"]),
                ("coil", "ResetPulse")]]),

    # ---------------- SECTION D - SAFETY-EVENT LATCHES ----------------
    dict(n=16, title="E-stop trip latch (seal-in; reset needs healthy circuit)",
         rung=[("or", [[("nc", "I_EStopOK")],
                       [("no", "EStopTrip")]]),
               ("or", [[("nc", "ResetPulse")],
                       [("nc", "I_EStopOK")]])],
         outs=[[("coil", "EStopTrip")]]),
    dict(n=17, title="Spill debounce",
         rung=[("no", "I_SpillDetect"),
               ("fb", "TON", "tDbSpill", ["IN", "PT:=cfgDebSpill"], ["Q"])],
         outs=[]),
    dict(n=18, title="Spill trip latch (reset refused while tray is wet)",
         rung=[("or", [[("no", "tDbSpill.Q")],
                       [("no", "SpillTrip")]]),
               ("or", [[("nc", "ResetPulse")],
                       [("no", "I_SpillDetect")]])],
         outs=[[("coil", "SpillTrip")]]),

    # ---------------- SECTION E - SENSOR PLAUSIBILITY ----------------
    dict(n=19, title="Bottle sensors: physically impossible combinations",
         rung=[("or", [[("no", "I_BottleHigh"), ("nc", "I_BottleLow")],
                       [("no", "I_BottleLow"), ("nc", "dbBottlePresent")],
                       [("no", "I_BottleHigh"), ("nc", "dbBottlePresent")]]),
               ("fb", "TON", "tDbBerr", ["IN", "PT:=cfgDebSensorErr"], ["Q"])],
         outs=[[("coil", "BottleSensErr")]]),
    dict(n=20, title="Syringe sensors: physically impossible combinations",
         rung=[("or", [[("no", "I_PlungerLow"), ("no", "I_PlungerHigh")],
                       [("no", "I_PlungerLow"), ("nc", "dbSyrPresent")],
                       [("no", "I_PlungerHigh"), ("nc", "dbSyrPresent")],
                       [("no", "dbSyrLocked"), ("nc", "dbSyrPresent")],
                       [("no", "dbTipPresent"), ("nc", "dbSyrPresent")]]),
               ("fb", "TON", "tDbSerr", ["IN", "PT:=cfgDebSensorErr"], ["Q"])],
         outs=[[("coil", "SyrSensErr")]]),
    dict(n=21, title="Any sensor plausibility error",
         rung=[("or", [[("no", "BottleSensErr")],
                       [("no", "SyrSensErr")]])],
         outs=[[("coil", "SensorErr")]]),

    # ---------------- SECTION F - READY & PERMISSIVE ----------------
    dict(n=22, title="Bottle package ready (full bottle refused, top-off allowed)",
         rung=[("no", "ModeBottle"), ("no", "dbBottlePresent"),
               ("nc", "I_BottleHigh"), ("nc", "SensorErr")],
         outs=[[("coil", "ReadyBottle")]]),
    dict(n=23, title="Syringe package ready",
         rung=[("no", "ModeSyringe"), ("no", "dbSyrPresent"), ("no", "dbSyrLocked"),
               ("no", "dbTipPresent"), ("nc", "I_PlungerHigh"), ("nc", "SensorErr")],
         outs=[[("coil", "ReadySyringe")]]),
    dict(n=24, title="Safety chain healthy",
         rung=[("no", "I_EStopOK"), ("nc", "EStopTrip"), ("nc", "SpillTrip"),
               ("nc", "FaultLatched")],
         outs=[[("coil", "SafetyOK")]]),
    dict(n=25, title="Start permissive (PotLow blocks NEW fills only)",
         rung=[("no", "SafetyOK"), ("no", "I_DoorClosed"), ("nc", "PotLow"),
               ("no", "StIdle"),
               ("or", [[("no", "ReadyBottle")],
                       [("no", "ReadySyringe")]])],
         outs=[[("coil", "PermStart")]]),

    # ---------------- SECTION G - SEQUENCE STATE MACHINE ----------------
    dict(n=26, title="Start: Idle -> Locking",
         rung=[("no", "StartPulse"), ("no", "PermStart")],
         outs=[[("set", "StLocking")]]),
    dict(n=27, title="Register package type + top-off for this cycle",
         rung=[("no", "StartPulse"), ("no", "PermStart")],
         outs=[[("no", "ReadyBottle"), ("set", "CycBottle")],
               [("no", "ReadyBottle"), ("no", "I_BottleLow"), ("set", "CycTopOff")],
               [("no", "ReadySyringe"), ("set", "CycSyringe")],
               [("no", "ReadySyringe"), ("nc", "I_PlungerLow"), ("set", "CycTopOff")]]),
    dict(n=28, title="Door lock supervision timer",
         rung=[("no", "StLocking"),
               ("fb", "TON", "tLockTO", ["IN", "PT:=cfgLockTimeout"], ["Q"])],
         outs=[]),
    dict(n=29, title="Lock engaged: Locking -> Filling",
         rung=[("no", "StLocking"), ("no", "I_DoorClosed"), ("no", "I_DoorLocked")],
         outs=[[("set", "StFilling")],
               [("rst", "StLocking")]]),
    dict(n=30, title="Fill watchdog - bottle",
         rung=[("no", "StFilling"), ("no", "CycBottle"),
               ("fb", "TON", "tFillB", ["IN", "PT:=cfgFillTimeoutBottle"], ["Q"])],
         outs=[]),
    dict(n=31, title="Fill watchdog - syringe",
         rung=[("no", "StFilling"), ("no", "CycSyringe"),
               ("fb", "TON", "tFillS", ["IN", "PT:=cfgFillTimeoutSyr"], ["Q"])],
         outs=[]),
    dict(n=32, title="Fill complete: RAW high-level + package still present",
         rung=[("no", "StFilling"),
               ("or", [[("no", "CycBottle"), ("no", "dbBottlePresent"),
                        ("no", "I_BottleHigh")],
                       [("no", "CycSyringe"), ("no", "dbSyrPresent"),
                        ("no", "I_PlungerHigh")]])],
         outs=[[("set", "StComplete")],
               [("rst", "StFilling")],
               [("set", "MDoneEvent")]]),
    dict(n=33, title="Package removed + buttons released: Complete -> Idle",
         rung=[("no", "StComplete"), ("nc", "I_BtnLeft"), ("nc", "I_BtnRight"),
               ("or", [[("no", "CycBottle"), ("nc", "dbBottlePresent")],
                       [("no", "CycSyringe"), ("nc", "dbSyrPresent")]])],
         outs=[[("rst", "StComplete")],
               [("rst", "CycBottle")],
               [("rst", "CycSyringe")]]),
    dict(n=34, title="Idle state (derived)",
         rung=[("nc", "StLocking"), ("nc", "StFilling"), ("nc", "StComplete"),
               ("nc", "FaultLatched"), ("nc", "EStopTrip"), ("nc", "SpillTrip")],
         outs=[[("coil", "StIdle")]]),

    # ---------------- SECTION H - FAULT CAPTURE & ABORT ----------------
    dict(n=35, title="Fault 1: E-stop (first-out capture)",
         rung=[("no", "EStopTrip")],
         outs=[[("box", "EQ", ["FaultCode", "0"]), ("mov", "1", "FaultCode")],
               [("set", "FaultLatched")]]),
    dict(n=36, title="Fault 3: spill",
         rung=[("no", "SpillTrip")],
         outs=[[("box", "EQ", ["FaultCode", "0"]), ("mov", "3", "FaultCode")],
               [("set", "FaultLatched")]]),
    dict(n=37, title="Fault 2: door opened/unlocked during cycle",
         rung=[("or", [[("no", "StLocking"), ("nc", "I_DoorClosed")],
                       [("no", "StFilling"), ("nc", "I_DoorClosed")],
                       [("no", "StFilling"), ("nc", "I_DoorLocked")]])],
         outs=[[("box", "EQ", ["FaultCode", "0"]), ("mov", "2", "FaultCode")],
               [("set", "FaultLatched")]]),
    dict(n=38, title="Fault 8: door lock failed to engage",
         rung=[("no", "tLockTO.Q")],
         outs=[[("box", "EQ", ["FaultCode", "0"]), ("mov", "8", "FaultCode")],
               [("set", "FaultLatched")]]),
    dict(n=39, title="Fault 4: fill watchdog timeout",
         rung=[("or", [[("no", "tFillB.Q")],
                       [("no", "tFillS.Q")]])],
         outs=[[("box", "EQ", ["FaultCode", "0"]), ("mov", "4", "FaultCode")],
               [("set", "FaultLatched")]]),
    dict(n=40, title="Fault 5: sensor plausibility error during cycle",
         rung=[("no", "SensorErr"),
               ("or", [[("no", "StLocking")],
                       [("no", "StFilling")]])],
         outs=[[("box", "EQ", ["FaultCode", "0"]), ("mov", "5", "FaultCode")],
               [("set", "FaultLatched")]]),
    dict(n=41, title="Fault 6: fixture/mode signal lost during cycle",
         rung=[("or", [[("no", "CycBottle"), ("nc", "ModeBottle")],
                       [("no", "CycSyringe"), ("nc", "ModeSyringe")]]),
               ("or", [[("no", "StLocking")],
                       [("no", "StFilling")]])],
         outs=[[("box", "EQ", ["FaultCode", "0"]), ("mov", "6", "FaultCode")],
               [("set", "FaultLatched")]]),
    dict(n=42, title="Fault 7: packaging lost/unclamped during cycle",
         rung=[("or", [[("no", "CycBottle"), ("nc", "dbBottlePresent")],
                       [("no", "CycSyringe"), ("nc", "dbSyrPresent")],
                       [("no", "CycSyringe"), ("nc", "dbSyrLocked")],
                       [("no", "CycSyringe"), ("nc", "dbTipPresent")]]),
               ("or", [[("no", "StLocking")],
                       [("no", "StFilling")]])],
         outs=[[("box", "EQ", ["FaultCode", "0"]), ("mov", "7", "FaultCode")],
               [("set", "FaultLatched")]]),
    dict(n=43, title="Any trip aborts the cycle immediately",
         rung=[("or", [[("no", "FaultLatched")],
                       [("no", "EStopTrip")],
                       [("no", "SpillTrip")]])],
         outs=[[("rst", "StLocking")],
               [("rst", "StFilling")],
               [("rst", "StComplete")]]),
    dict(n=44, title="Fault reset (3 s two-hand hold)",
         rung=[("no", "ResetPulse"), ("no", "I_EStopOK"), ("nc", "I_SpillDetect")],
         outs=[[("rst", "FaultLatched")],
               [("rst", "CycBottle")],
               [("rst", "CycSyringe")],
               [("rst", "CycTopOff")],
               [("mov", "0", "FaultCode")]]),

    # ---------------- SECTION I - OUTPUTS ----------------
    dict(n=45, title="Bottle fill valve (safety chain + interlocks in series)",
         rung=[("no", "StFilling"), ("no", "CycBottle"), ("no", "SafetyOK"),
               ("no", "I_DoorClosed"), ("no", "I_DoorLocked"), ("nc", "I_BottleHigh")],
         outs=[[("coil", "Q_ValveBottle")]]),
    dict(n=46, title="Syringe fill valve",
         rung=[("no", "StFilling"), ("no", "CycSyringe"), ("no", "SafetyOK"),
               ("no", "I_DoorClosed"), ("no", "I_DoorLocked"), ("nc", "I_PlungerHigh")],
         outs=[[("coil", "Q_ValveSyringe")]]),
    dict(n=47, title="Door lock solenoid",
         rung=[("or", [[("no", "StLocking")],
                       [("no", "StFilling")]])],
         outs=[[("coil", "Q_DoorLock")]]),
    dict(n=48, title="Mode lamp - bottle",
         rung=[("no", "ModeBottle")],
         outs=[[("coil", "Q_LampBottle")]]),
    dict(n=49, title="Mode lamp - syringe",
         rung=[("no", "ModeSyringe")],
         outs=[[("coil", "Q_LampSyringe")]]),
    dict(n=50, title="Filling lamp mirrors the actual valve commands",
         rung=[("or", [[("no", "Q_ValveBottle")],
                       [("no", "Q_ValveSyringe")]])],
         outs=[[("coil", "Q_LampFilling")]]),
    dict(n=51, title="Done lamp",
         rung=[("no", "StComplete")],
         outs=[[("coil", "Q_LampDone")]]),
    dict(n=52, title="E-stop lamp (steady)",
         rung=[("or", [[("nc", "I_EStopOK")],
                       [("no", "EStopTrip")]])],
         outs=[[("coil", "Q_LampEStop")]]),
    dict(n=53, title='"Operator interaction required" conditions',
         rung=[("or", [[("no", "FaultLatched")],
                       [("no", "SpillTrip")],
                       [("no", "PotLow")],
                       [("no", "SensorErr")],
                       [("no", "THC_Lockout")],
                       [("no", "EStopTrip"), ("no", "I_EStopOK")]])],
         outs=[[("coil", "AttnReq")]]),
    dict(n=54, title="Attention lamp = condition AND flasher",
         rung=[("no", "AttnReq"), ("no", "Blink")],
         outs=[[("coil", "Q_LampAttention")]]),

    # ---------------- SECTION J - PRODUCTION COUNTERS ----------------
    dict(n=55, title="Bottle counter (PV=65535: free-running)",
         rung=[("no", "MDoneEvent"), ("no", "CycBottle"),
               ("fb", "CTU", "ctrBottle",
                ["CU", "RESET:=cmdCounterReset", "PV:=65535"],
                ["Q", "CV->CntBottles"])],
         outs=[]),
    dict(n=56, title="Syringe counter",
         rung=[("no", "MDoneEvent"), ("no", "CycSyringe"),
               ("fb", "CTU", "ctrSyringe",
                ["CU", "RESET:=cmdCounterReset", "PV:=65535"],
                ["Q", "CV->CntSyringes"])],
         outs=[]),
    dict(n=57, title="Consume the completion event",
         rung=[("no", "MDoneEvent")],
         outs=[[("rst", "MDoneEvent")]]),
    dict(n=58, title="Consume the HMI counter-reset command",
         rung=[("no", "cmdCounterReset")],
         outs=[[("rst", "cmdCounterReset")]]),
]

SECTIONS = {
    "A": (1, 2, "System utilities"),
    "B": (3, 9, "Input conditioning (debounce)"),
    "C": (10, 15, "Two-hand control & reset gesture"),
    "D": (16, 18, "Safety-event latches"),
    "E": (19, 21, "Sensor plausibility (false-positive defence)"),
    "F": (22, 25, "Ready conditions & start permissive"),
    "G": (26, 34, "Sequence state machine"),
    "H": (35, 44, "Fault capture (first-out) & cycle abort"),
    "I": (45, 54, "Outputs"),
    "J": (55, 58, "Production counters"),
}
